# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c8f836d364bce04ae8e2c18688aded4b6a11b288dfdfc2f6f50fdf471b8ec3181df0fdfe9cb41ef963713146109da0fc6798c8df810bdfede3b9ac0c09002dd

test:
  secret_key_base: d08ae11241104ee4a54498d8a9f6f03a1e2468fa478ae3fbcdff9bf8d75fd1342ee6d45d0a081de9c712fc7e39c1c7d44891e1a8534ebc20273ad1ba07eb5df9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
